"""empty message

Revision ID: c26851812efd
Revises: 
Create Date: 2023-08-21 12:13:04.519031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26851812efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('block', sa.String(length=50), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('food_items', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_description', sa.String(length=250), nullable=True),
    sa.Column('locationid', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.String(length=250), nullable=True),
    sa.Column('zip_codes', sa.String(length=250), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('facility_type', sa.String(length=50), nullable=True),
    sa.Column('expiration_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truck')
    # ### end Alembic commands ###
